namespace LimeLibrary.System {

public enum InputBindingType {
  /// <summary>
  /// GamePad
  /// </summary>
  GamePadButtonEast = 0,
  GamePadButtonNorth = 1,
  GamePadButtonSouth = 2,
  GamePadButtonWest = 3,
  GamePadLeftShoulder = 4,
  GamePadLeftTrigger = 5,
  GamePadRightShoulder = 6,
  GamePadRightTrigger = 7,
  GamePadDPad = 8,
  GamePadDPadDown = 9,
  GamePadDPadLeft = 10,
  GamePadDPadRight = 11,
  GamePadDPadUp = 12,
  GamePadDPadX = 13,
  GamePadDPadY = 14,
  GamePadLeftStick = 15,
  GamePadLeftStickDown = 16,
  GamePadLeftStickLeft = 17,
  GamePadLeftStickRight = 18,
  GamePadLeftStickUp = 19,
  GamePadLeftStickX = 20,
  GamePadLeftStickY = 21,
  GamePadLeftStickPress = 22,
  GamePadRightStick = 23,
  GamePadRightStickDown = 24,
  GamePadRightStickLeft = 25,
  GamePadRightStickRight = 26,
  GamePadRightStickUp = 27,
  GamePadRightStickX = 28,
  GamePadRightStickY = 29,
  GamePadRightStickPress = 30,
  GamePadStart = 31,
  GamePadSelect = 32,

  /// <summary>
  /// Key
  /// </summary>
  Escape = 50,
  Tab = 51,
  Shift = 52,
  Space = 53,
  Control = 54,
  Alt = 55,
  CapsLock = 56,
  Backspace = 57,
  Enter = 58,
  W = 60,
  A = 61,
  S = 62,
  D = 63,
  R = 64,
  Q = 65,
  Z = 66,
  X = 67,
  C = 68,
  E = 69,
  T = 70,
  F = 71,
  B = 72,
  G = 73,
  H = 74,
  I = 75,
  J = 76,
  K = 77,
  L = 78,
  M = 79,
  N = 80,
  O = 81,
  P = 82,
  U = 83,
  V = 84,
  Y = 85,
  Number1 = 90,
  Number2,
  Number3,
  Number4,
  Number5,
  Number6,
  Number7,
  Number8,
  Number9,
  Number0,
  Function1 = 100,
  Function2,
  Function3,
  Function4,
  Function5,
  Function6,
  Function7,
  Function8,
  Function9,
  Function10,
  Function11,
  Function12,
  Semicolon = 112,
  Comma,
  Period,
  Slash,
  Insert = 130,
  Delete,
  Home,
  End,
  PageUp,
  PageDown,
  ArrowUp,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  NumLock = 140,
  NumPadDivide,
  NumPadMultiply,
  NumPadMinus,
  NumPadPlus,
  NumPadEnter,
  NumPad0,
  NumPad1,
  NumPad2,
  NumPad3,
  NumPad4,
  NumPad5,
  NumPad6,
  NumPad7,
  NumPad8,
  NumPad9,

  /// <summary>
  /// Mouse
  /// </summary>
  LeftClick = 200,
  RightClick = 201,
  MousePointer = 202,
}

}